allprojects {
    repositories {
        google()
        mavenCentral()

        // Mozilla GeckoView Maven repository
        maven {
            url "https://maven.mozilla.org/maven2/"
        }
    }
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
